import {
  ObsConnectionInfoSchema,
  ObsControlError,
  ObsObservedCatalogSchema,
  ObsObservedProgramSceneSchema,
  ObsObservedRecordStatusSchema,
  ObsObservedStreamStatusSchema,
  type ObsConnectionInfo,
  type ObsControlErrorCode,
  type ObsControlPort,
  type ObsObservedCatalog,
  type ObsObservedProgramScene,
  type ObsObservedRecordStatus,
  type ObsObservedStreamStatus,
  type ObsSetInputMuteArgs,
  type ObsSetSceneItemEnabledArgs
} from "./control-port.js";
import type {
  ObsConnectionRef,
  ObsRecordingStatus,
  ObsStreamStatus
} from "../../domain/obs/index.js";

/**
 * Configurable in-memory `ObsControlPort` fake — the slice-5 test double that
 * stands in for a live OBS instance with **no real obs-websocket dependency**.
 *
 * It simulates one OBS instance: a configurable scene / source / scene-item
 * catalog, a current program scene, and coarse stream + recording state. It
 * applies scene switches, source/scene-item toggles, and stream/recording
 * start-stop **deterministically** (no clock of its own — any timestamp is
 * injected), records every call for assertions, and returns only Zod-validated,
 * secret-free results. Per-operation **failure injection** (`disconnected`,
 * `action-rejected`, `not-found`, `port-failure`) lets later slices exercise the
 * error classifier and the graceful-degradation paths. Every injected failure is
 * surfaced as a typed, redacted `ObsControlError` whose `safeMessage` carries no
 * secret, URL, or raw connection detail.
 *
 * This is the OBS analog of Community+'s `defaultSendPort` fake, scaled up to a
 * stateful instance so the action-gate slices (6–9) can drive realistic state
 * transitions, and it doubles as the seed for `packages/obs-agent` test fixtures.
 */
export interface FakeObsSceneConfig {
  readonly displayName: string;
  readonly obsSceneRef: string;
}

export interface FakeObsSourceConfig {
  readonly activeHint?: boolean;
  readonly kindLabel: string;
  readonly mutedHint?: boolean;
  readonly obsSourceRef: string;
}

export interface FakeObsSceneItemConfig {
  readonly obsSceneItemId: string;
  readonly obsSceneRef: string;
  readonly obsSourceRef: string;
  readonly visibleHint: boolean;
}

/**
 * The operations failure injection can target. `connect` covers the session
 * handshake; the read operations cover catalog/status refreshes; the
 * output-affecting operations cover dispatch. A `disconnected` failure mode is the
 * graceful-degradation trigger the service surfaces as `OBS_DISCONNECTED`.
 */
export type FakeObsOperation =
  | "connect"
  | "disconnect"
  | "getCurrentProgramScene"
  | "getRecordStatus"
  | "getSceneList"
  | "getStreamStatus"
  | "setCurrentProgramScene"
  | "setInputMute"
  | "setSceneItemEnabled"
  | "startRecord"
  | "startStream"
  | "stopRecord"
  | "stopStream";

/**
 * An injected failure: the typed `code` to surface and an optional `retryable`
 * override (defaults follow the code — `disconnected` is retryable, the rest
 * terminal). The `safeMessage` is generated by the fake and is always redacted;
 * a caller cannot inject a message, so no secret can be smuggled into the error.
 */
export interface FakeObsFailure {
  readonly code: ObsControlErrorCode;
  readonly retryable?: boolean;
}

/**
 * One recorded port call: the method name, the `connectionRef` it was given, and
 * an optional opaque argument summary (refs + coarse flags only, never a secret).
 * Tests assert call recording and ordering against this list.
 */
export interface FakeObsControlCall {
  readonly args?: Readonly<Record<string, string | boolean>>;
  readonly connectionRef: string;
  readonly operation: FakeObsOperation;
}

export interface FakeObsControlPortConfig {
  readonly currentProgramSceneRef?: string;
  readonly failures?: Partial<Record<FakeObsOperation, FakeObsFailure>>;
  readonly recordingStatus?: ObsRecordingStatus;
  readonly scenes?: readonly FakeObsSceneConfig[];
  readonly sceneItems?: readonly FakeObsSceneItemConfig[];
  readonly sources?: readonly FakeObsSourceConfig[];
  readonly streamStatus?: ObsStreamStatus;
}

/**
 * The fake port plus its inspection + control surface. The `port` is the
 * `ObsControlPort` the service depends on; the rest let a test read the simulated
 * instance state, the recorded calls, and re-inject or clear failures between
 * assertions — all deterministic.
 */
export interface FakeObsControlPort {
  readonly calls: () => readonly FakeObsControlCall[];
  readonly clearFailure: (operation: FakeObsOperation) => void;
  readonly currentProgramSceneRef: () => string | undefined;
  readonly port: ObsControlPort;
  readonly recordingStatus: () => ObsRecordingStatus;
  readonly setFailure: (
    operation: FakeObsOperation,
    failure: FakeObsFailure
  ) => void;
  readonly streamStatus: () => ObsStreamStatus;
}

const DEFAULT_RETRYABLE_BY_CODE: Readonly<Record<ObsControlErrorCode, boolean>> =
  {
    "action-rejected": false,
    disconnected: true,
    "not-found": false,
    "port-failure": false
  };

/**
 * The fixed, redacted operator message per failure code. Generated here (never
 * caller-supplied), so an `ObsControlError` can carry no secret, URL, or raw
 * connection detail — only a coarse, safe description.
 */
const SAFE_MESSAGE_BY_CODE: Readonly<Record<ObsControlErrorCode, string>> = {
  "action-rejected": "OBS rejected the requested action.",
  disconnected: "The OBS instance is not reachable.",
  "not-found": "The referenced OBS scene, source, or scene-item was not found.",
  "port-failure": "The OBS control connection failed."
};

const failureToError = (failure: FakeObsFailure): ObsControlError =>
  new ObsControlError(
    failure.code,
    SAFE_MESSAGE_BY_CODE[failure.code],
    failure.retryable ?? DEFAULT_RETRYABLE_BY_CODE[failure.code]
  );

interface MutableSceneItem {
  obsSceneItemId: string;
  obsSceneRef: string;
  obsSourceRef: string;
  visibleHint: boolean;
}

interface MutableSource {
  activeHint?: boolean;
  kindLabel: string;
  mutedHint?: boolean;
  obsSourceRef: string;
}

export const createFakeObsControlPort = (
  config: FakeObsControlPortConfig = {}
): FakeObsControlPort => {
  const scenes = (config.scenes ?? []).map((scene) => ({ ...scene }));
  const sources: MutableSource[] = (config.sources ?? []).map((source) => ({
    kindLabel: source.kindLabel,
    obsSourceRef: source.obsSourceRef,
    ...(source.activeHint !== undefined ? { activeHint: source.activeHint } : {}),
    ...(source.mutedHint !== undefined ? { mutedHint: source.mutedHint } : {})
  }));
  const sceneItems: MutableSceneItem[] = (config.sceneItems ?? []).map(
    (sceneItem) => ({ ...sceneItem })
  );

  let currentProgramSceneRef = config.currentProgramSceneRef;
  let streamStatus: ObsStreamStatus = config.streamStatus ?? "inactive";
  let recordingStatus: ObsRecordingStatus = config.recordingStatus ?? "inactive";

  const failures = new Map<FakeObsOperation, FakeObsFailure>();
  for (const [operation, failure] of Object.entries(config.failures ?? {})) {
    failures.set(operation as FakeObsOperation, failure);
  }

  const calls: FakeObsControlCall[] = [];

  const record = (
    operation: FakeObsOperation,
    connectionRef: ObsConnectionRef,
    args?: Readonly<Record<string, string | boolean>>
  ): void => {
    calls.push({
      connectionRef,
      operation,
      ...(args !== undefined ? { args } : {})
    });
  };

  /**
   * Record the call, then reject (deterministically) if a failure is injected for
   * this operation. Recording *before* the failure check means a test can assert
   * that a rejected dispatch still reached the port — the error classifier and
   * the audit trail both need that.
   */
  const guard = (
    operation: FakeObsOperation,
    connectionRef: ObsConnectionRef,
    args?: Readonly<Record<string, string | boolean>>
  ): ObsControlError | undefined => {
    record(operation, connectionRef, args);
    const failure = failures.get(operation);

    return failure === undefined ? undefined : failureToError(failure);
  };

  const observedCatalog = (): ObsObservedCatalog =>
    // Build plain (unbranded) literals; the schema brands the opaque refs on
    // parse. The config takes plain strings so callers never hand-brand a ref.
    ObsObservedCatalogSchema.parse({
      scenes: scenes.map((scene) => ({
        displayName: scene.displayName,
        isCurrentProgramScene: scene.obsSceneRef === currentProgramSceneRef,
        obsSceneRef: scene.obsSceneRef
      })),
      sceneItems: sceneItems.map((sceneItem) => ({
        obsSceneItemId: sceneItem.obsSceneItemId,
        obsSceneRef: sceneItem.obsSceneRef,
        obsSourceRef: sceneItem.obsSourceRef,
        visibleHint: sceneItem.visibleHint
      })),
      sources: sources.map((source) => ({
        kindLabel: source.kindLabel,
        obsSourceRef: source.obsSourceRef,
        ...(source.activeHint !== undefined
          ? { activeHint: source.activeHint }
          : {}),
        ...(source.mutedHint !== undefined
          ? { mutedHint: source.mutedHint }
          : {})
      })),
      ...(currentProgramSceneRef !== undefined
        ? { currentProgramSceneRef }
        : {})
    });

  const streamResult = (): ObsObservedStreamStatus =>
    ObsObservedStreamStatusSchema.parse({ streamStatus });

  const recordResult = (): ObsObservedRecordStatus =>
    ObsObservedRecordStatusSchema.parse({ recordingStatus });

  const port: ObsControlPort = {
    connect: (connectionRef): Promise<ObsConnectionInfo> => {
      const error = guard("connect", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      return Promise.resolve(
        ObsConnectionInfoSchema.parse({
          connectionStatus: "connected",
          obsWebsocketVersion: "5.0.0"
        })
      );
    },

    disconnect: (connectionRef): Promise<void> => {
      const error = guard("disconnect", connectionRef);

      return error === undefined ? Promise.resolve() : Promise.reject(error);
    },

    getCurrentProgramScene: (
      connectionRef
    ): Promise<ObsObservedProgramScene> => {
      const error = guard("getCurrentProgramScene", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      if (currentProgramSceneRef === undefined) {
        return Promise.reject(failureToError({ code: "not-found" }));
      }

      return Promise.resolve(
        ObsObservedProgramSceneSchema.parse({ currentProgramSceneRef })
      );
    },

    getRecordStatus: (connectionRef): Promise<ObsObservedRecordStatus> => {
      const error = guard("getRecordStatus", connectionRef);

      return error === undefined
        ? Promise.resolve(recordResult())
        : Promise.reject(error);
    },

    getSceneList: (connectionRef): Promise<ObsObservedCatalog> => {
      const error = guard("getSceneList", connectionRef);

      return error === undefined
        ? Promise.resolve(observedCatalog())
        : Promise.reject(error);
    },

    getStreamStatus: (connectionRef): Promise<ObsObservedStreamStatus> => {
      const error = guard("getStreamStatus", connectionRef);

      return error === undefined
        ? Promise.resolve(streamResult())
        : Promise.reject(error);
    },

    setCurrentProgramScene: (connectionRef, obsSceneRef): Promise<void> => {
      const error = guard("setCurrentProgramScene", connectionRef, {
        obsSceneRef
      });
      if (error !== undefined) {
        return Promise.reject(error);
      }

      if (!scenes.some((scene) => scene.obsSceneRef === obsSceneRef)) {
        return Promise.reject(failureToError({ code: "not-found" }));
      }

      currentProgramSceneRef = obsSceneRef;

      return Promise.resolve();
    },

    setInputMute: (
      connectionRef,
      args: ObsSetInputMuteArgs
    ): Promise<void> => {
      const error = guard("setInputMute", connectionRef, {
        muted: args.muted,
        obsSourceRef: args.obsSourceRef
      });
      if (error !== undefined) {
        return Promise.reject(error);
      }

      const source = sources.find(
        (entry) => entry.obsSourceRef === args.obsSourceRef
      );
      if (source === undefined) {
        return Promise.reject(failureToError({ code: "not-found" }));
      }

      source.mutedHint = args.muted;

      return Promise.resolve();
    },

    setSceneItemEnabled: (
      connectionRef,
      args: ObsSetSceneItemEnabledArgs
    ): Promise<void> => {
      const error = guard("setSceneItemEnabled", connectionRef, {
        enabled: args.enabled,
        obsSceneItemId: args.obsSceneItemId,
        obsSceneRef: args.obsSceneRef
      });
      if (error !== undefined) {
        return Promise.reject(error);
      }

      const sceneItem = sceneItems.find(
        (entry) =>
          entry.obsSceneRef === args.obsSceneRef &&
          entry.obsSceneItemId === args.obsSceneItemId
      );
      if (sceneItem === undefined) {
        return Promise.reject(failureToError({ code: "not-found" }));
      }

      sceneItem.visibleHint = args.enabled;

      return Promise.resolve();
    },

    startRecord: (connectionRef): Promise<ObsObservedRecordStatus> => {
      const error = guard("startRecord", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      recordingStatus = "active";

      return Promise.resolve(recordResult());
    },

    startStream: (connectionRef): Promise<ObsObservedStreamStatus> => {
      const error = guard("startStream", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      streamStatus = "active";

      return Promise.resolve(streamResult());
    },

    stopRecord: (connectionRef): Promise<ObsObservedRecordStatus> => {
      const error = guard("stopRecord", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      recordingStatus = "inactive";

      return Promise.resolve(recordResult());
    },

    stopStream: (connectionRef): Promise<ObsObservedStreamStatus> => {
      const error = guard("stopStream", connectionRef);
      if (error !== undefined) {
        return Promise.reject(error);
      }

      streamStatus = "inactive";

      return Promise.resolve(streamResult());
    }
  };

  return {
    calls: (): readonly FakeObsControlCall[] => [...calls],
    clearFailure: (operation): void => {
      failures.delete(operation);
    },
    currentProgramSceneRef: (): string | undefined => currentProgramSceneRef,
    port,
    recordingStatus: (): ObsRecordingStatus => recordingStatus,
    setFailure: (operation, failure): void => {
      failures.set(operation, failure);
    },
    streamStatus: (): ObsStreamStatus => streamStatus
  };
};
